=== lichtflut/resource-hub/rest-api/src/main/resources/xsd/api-structures.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Copyright (C) 2013 lichtflut Forschungs- und Entwicklungsgesellschaft mbH

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://rb.lichtflut.de/ns#ServiceAPI" xmlns="http://rb.lichtflut.de/ns#ServiceAPI">

	<xs:element name="systemDomain" type="systemDomain" />

	<xs:element name="systemIdentity" type="systemIdentity" />

	<xs:complexType name="systemDomain">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="domainAdministrator" type="systemIdentity"
				minOccurs="0" />
			<xs:element name="domainIdentifier" type="xs:string"
				minOccurs="0" />
			<xs:element name="domesticDomain" type="xs:boolean" />
			<xs:element name="title" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="systemIdentity">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="password" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="username" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== lichtflut/resource-hub/rest-api/src/test/resources/domain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2013 lichtflut Forschungs- und Entwicklungsgesellschaft mbH

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<p:systemDomain xmlns:p="http://rb.lichtflut.de/ns#ServiceAPI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rb.lichtflut.de/ns#ServiceAPI ../../main/resources/xsd/api-structures.xsd ">
  <description>description</description>
  <domainAdministrator>
    <id>id</id>
    <password>password</password>
    <username>username</username>
  </domainAdministrator>
  <domainIdentifier>domainIdentifier</domainIdentifier>
  <domesticDomain>true</domesticDomain>
  <title>title</title>
</p:systemDomain>
